name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  release:
    types:
      - released

jobs:
  test-closures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          set -eux

          # Ensure all the checks can be built without internet
          nix flake check
          nix build .#tarballs_json
          cat result

          nix build .#closures_json
          cat result

          nix build .#closures_nix
          cat result

  build-versions-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          set -eux

          # Ensure all the checks can be built without internet
          nix flake check
          nix build .#tarballs_json
          cat result

          nix build .#closures_json
          cat result

          nix build .#closures_nix
          cat result

  publish:
    needs: [test-closures, build-versions-nix]
    environment: ${{ github.event_name == 'release' && 'production' || '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          set -eux

          nix build .#closures_nix
          cat result

          mkdir ./artifacts
          cat './result' > './artifacts/universal'
          nix eval -f ./artifacts/universal

      - uses: DeterminateSystems/push-artifact-ids@main
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
        with:
          s3_upload_role: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          bucket: ${{ secrets.AWS_S3_UPLOAD_BUCKET }}
          directory: ./artifacts
          ids_project_name: nix-upgrade
          ids_binary_prefix: determinate-nix-versions.nix

      - uses: "DeterminateSystems/flakehub-push@main"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          visibility: "public"
          name: "DeterminateSystems/nix"
          tag: "${{ github.ref_name }}"
