name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    runs-on: macos-12
    permissions:
      contents: read
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir ./artifacts
          cp './versions.nix' './artifacts/universal'

      - uses: DeterminateSystems/push-artifact-ids@main
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
        with:
          s3_upload_role: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          bucket: ${{ secrets.AWS_S3_UPLOAD_BUCKET }}
          directory: ./artifacts
          ids_project_name: nix-upgrade
          ids_binary_prefix: determinate-nix-versions.nix
