name: Build Test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          set -eux

          cd tests
          rm -f flake.lock
          nix flake lock
          nix flake check
